image: "rust:latest"

stages:
- test
- deploy_docs

test:stable:
  before_script:
  - apt-get update -yqq
  - apt-get install -yqq libluajit-5.1-dev
  - rustup toolchain add stable
  script:
  - cargo +stable test
  stage: test
test:beta:
  before_script:
  - apt-get update -yqq
  - apt-get install -yqq libluajit-5.1-dev
  - rustup toolchain add beta
  script:
  - cargo +beta test
  stage: test
test:nightly:
  before_script:
  - apt-get update -yqq
  - apt-get install -yqq libluajit-5.1-dev
  - rustup toolchain add nightly
  script:
  - cargo +nightly test
  stage: test

pages:
  script:
  - cargo doc
  - mkdir docs
  - mv target/doc/* docs
  stage: deploy_docs
  artifacts:
    paths:
    - docs/               
  only:
  - master 