language: rust
rust:
  - stable
  - beta
  - nightly
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libluajit-5.1-dev
before_deploy:
  - cargo doc
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: target/doc/
  on:
    branch: master
    rust: stable